version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
configuration: Debug
image: Visual Studio 2017
platform: x86
build:
  project: DrWin.sln
  verbosity: minimal
artifacts:
  - path: Drwin.exe
    name: Drwin.exe
environment:
  global:
    # WarningLevel of 1 is ONLY SEVERE warnings, nothing else. See
    # https://stackoverflow.com/questions/1023858/how-to-suppress-specific-msbuild-warning
    MSBUILD_FLAGS: /maxcpucount /nologo /property:WarningLevel=1
